<?php
/**
* @author : PS
* @Date : 23nd April'20
* @Description : Add the payment logos static blocks to the product page
* @link : https://trello.com/c/vz1chOWu/81-frontpage-templating-programmierung
*/
?>
<?php $_product = $block->getProduct();?>
<div class="pos-payment-logos">
    <div class="inner-container">
        <?php
            echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('payment-logo-product-page')
                    ->toHtml();
        ?>
    </div>
</div>