<?php
/**
* @author : PS
* @Date : 23nd April'20
* @Description : Add the social share option to the product page
* @link : https://trello.com/c/vz1chOWu/81-frontpage-templating-programmierung
*/
?>
<?// $block var Magento\Catalog\Block\Product\View ?>
<?php 
    $_product = $block->getProduct();
    $productName = $_product->getName();
    $productUrl = $_product->getProductUrl();
?>

    <a href="javascript:void(0)" onClick="window.open('https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($productUrl); ?>&amp;t=<?php echo urlencode($productName); ?>', 'facebook', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes')" title="<?php echo __('Share on Facebook') ?>"><img src="/pub/media/wysiwyg/social-share/facebook.jpg" alt="Auf Facebook teilen"></a>
    <!-- Twitter -->
    <a href="javascript:void(0);" onClick="window.open('http://twitter.com/home/?status=<?php echo urlencode($productName . ' (' . $productUrl . ')'); ?>', 'twitter', 'width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes')" title="<?php echo __('Tweet') ?>"><img src="/pub/media/wysiwyg/social-share/twitter.jpg" alt="Auf Twitter teilen"></a>  