<?php
/**
 * Add the Products Tab template to add the lcustom attribute information 
 * PM PS, 27.04.20, @link - https://trello.com/c/vz1chOWu/81-frontpage-templating-programmierung
 */
?>
<?php /** var @block Magento\Catalog\Block\Product\View */?>
<?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
<?php $_product = $this->getProduct(); ?>
<?php if ($_product->getTabFinanzierung()):?>
    <div class="std">
		<?php echo $_helper->productAttribute($_product, nl2br($_product->getTabFinanzierung()), 'tab_finanzierung') ?>
    </div>
<?php endif;?>