<?php 
/**
 * Search Suite Autocomplete Template File to load the UI components.
 * PM PS, 30.04.20, @link - https://trello.com/c/fR4dyPJV/96-styling-der-basissuchfunktion-im-standard-von-magento-styling-of-magento-default-search-functionality
 */

/**@var Pixelmechanics\SearchAutocomplete\Block\Autocomplete $block  */
?>

<div data-bind="scope: 'searchsuiteautocomplete_form'">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>

<?// Initialize the UI components to load the KO templates with Data Providers ?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "searchsuiteautocomplete_form": {
                    "component": "Pixelmechanics_SearchAutocomplete/js/autocomplete"
                },
                "searchsuiteautocompleteBindEvents": {
                    "component": "Pixelmechanics_SearchAutocomplete/js/bindEvents",
                    "config": {
                        "searchFormSelector": "#search_mini_form",
                        "searchButtonSelector": "button.search",
                        "inputSelector": "#search, #mobile_search, .minisearch input[type=\"text\"]",
                        "searchDelay": "<?php echo $block->escapeHtml($block->getSearchDelay()) ?>"
                    }
                },
                "searchsuiteautocompleteDataProvider": {
                    "component": "Pixelmechanics_SearchAutocomplete/js/dataProvider",
                    "config": {
                        "url": "<?php echo $block->escapeUrl($block->getSearchUrl()) ?>"
                    }
                }
            }
        }
    }
}
</script>