<?php
/**
 * Überschreiben Sie die Vorlage, um das Steuerpreisformat zu ändern
 * PM JM - 17.07.20 - @link : https://trello.com/c/Qug4TsMq/145-erweiterung-produktdetailseite-adjustments-productdetailpage
 */
?>

<?php /** @var \Magento\Tax\Pricing\Render\Adjustment $block */ ?>

<?php if ($block->displayBothPrices()) : ?>
    <span id="<?= $block->escapeHtmlAttr($block->buildIdWithPrefix('price-excluding-tax-')) ?>"
          data-label="<?= $block->escapeHtmlAttr(__('Excl. Tax')) ?>"
          data-price-amount="<?= /* @noEscape */ $block->getRawAmount() ?>"
          data-price-type="basePrice"
          class="price-wrapper price-excluding-tax-custom">
        <span class="price"><?= /* @noEscape */ $block->getDisplayAmountExclTax() ?></span></span>
        <span class="vat-txt">(<?=__('netto')?>)</span>
<?php endif; ?>
