<?php
/**
* @author : PS
* @Date : 16th April'20
* @Description : Override the Firegento Magesetup price template to load additional prices.
* @link : https://trello.com/c/vz1chOWu/81-frontpage-templating-programmierung
*/

/**
 * @var $this \FireGento\MageSetup\Block\Price\Details
 */
?>
<?php
$shippingCostUrl = $this->getShippingCostUrl();
$taxRate = $this->getFormattedTaxRate();
?>
<div class="price-details">
    <?php if ($shippingCostUrl && $this->canShowShippingLink()): ?>
        <?php if ($this->getPriceDisplayType() == \Magento\Tax\Model\Config::DISPLAY_TYPE_EXCLUDING_TAX): ?>
            <?php if ($this->isIncludingShippingCosts()): ?>
                <span class="tax-detailsz"><?php echo __('Excl. %1 VAT', $taxRate) ?><span class="tax-separator">, </span><span class="shipping-cost-details"><?php echo __('incl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?></span></span>
            <?php else: ?>
                <span class="tax-details"><?php echo __('Excl. %1 VAT', $taxRate) ?><span class="tax-separator">, </span><span class="shipping-cost-details"><?php echo __('excl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?></span></span>
            <?php endif ?>
        <?php elseif ($this->getPriceDisplayType() == \Magento\Tax\Model\Config::DISPLAY_TYPE_INCLUDING_TAX): ?>
            <?php if ($this->isIncludingShippingCosts()): ?>
                <span class="tax-details"><?php echo __('Incl. %1 VAT', $taxRate) ?><span class="tax-separator">, </span><span class="shipping-cost-details"><?php echo __('incl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?></span></span>
            <?php else: ?>
                <span class="tax-details"><?php echo __('Incl. %1 VAT', $taxRate) ?><span class="tax-separator">, </span><span class="shipping-cost-details"><?php echo __('excl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?></span></span>
            <?php endif ?>
        <?php elseif ($this->getPriceDisplayType() == \Magento\Tax\Model\Config::DISPLAY_TYPE_BOTH): ?>
            <?php if ($this->isIncludingShippingCosts()): ?>
                <span class="tax-details"><?php echo __('incl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?></span>
            <?php else: ?>
                <span class="tax-details"><?php echo __('excl. <a href="%1">Shipping Cost</a>', $shippingCostUrl) ?></span>
            <?php endif ?>
        <?php endif ?>
    <?php else: ?>
        <?php if ($this->getPriceDisplayType() == \Magento\Tax\Model\Config::DISPLAY_TYPE_EXCLUDING_TAX): ?>
            <span class="tax-details"><?php echo __('Excl. %1 VAT', $taxRate) ?></span>
        <?php elseif ($this->getPriceDisplayType() == \Magento\Tax\Model\Config::DISPLAY_TYPE_INCLUDING_TAX): ?>
            <span class="tax-details"><?php echo __('Incl. %1 VAT', $taxRate) ?></span>
        <?php endif ?>
    <?php endif ?>
</div>